### Create a new course
POST http://localhost:8080/course
Content-Type: application/json

{
  "name": "Introduction to d++",
  "description": "Introduction to graphic design principles and tools.",
  "duration": 40,
  "price": 150.00
}


### Filter
POST http://localhost:8080/course/filter?page=1&size=6
Content-Type: application/json

{
  "price": 100,
  "duration": 40,
  "createdDateFrom": "1996-08-01",
  "createdDateTo": "2024-10-17"

}


### Get all courses
GET http://localhost:8080/course?page=0&size=3

### Get a course by ID
GET http://localhost:8080/course/22

### Delete a course by ID
DELETE http://localhost:8080/course/3

### Update a course by ID
PUT http://localhost:8080/course/1
Content-Type: application/json

{
  "name": "Cybersecurity Essentials",
  "description": "Learn the basics of cybersecurity.",
  "duration": 30,
  "price": 135.50
}


### Get courses by name
GET http://localhost:8080/course/name?name=Introduction to Java

### Get course by price
GET http://localhost:8080/course/price/100?page=1&size=2

### Get course by duration
GET http://localhost:8080/course/duration?duration=40

### Get course list between two prices
GET http://localhost:8080/course/price-range?min=101.00&max=150.00

### Get course list between two created dates
GET http://localhost:8080/course/date-range?startDate=1996-08-01&endDate=2024-10-15

###
 GET localhost